language: r
cache: packages
sudo: false
env:
  global:
  - secure: JcXZoVFerbIqDTUmpV//c4fhHx9cdYZByYWzYsfE1J3eDASWiq8Js+Om1t7L6jZCz4bAZr0ic7SxWmptEgaa9dDmnIx+w9YOTFzBImrKksHkl3hy5KmMGU/zcMJnueY1ESxKZ0QdB5hyqJpOZ7cs4fxrykFHGwWJMNMTFHvR/0DplLXyGjmAHtyZF0/hKZE9zGioq2yxfideG174Og6tB7ojCq+rAqu+8Su2aoSNHDYuXgYakToPFlTG56zuRNbS11QzEScjl0UsdgT8g3VNy7Zk8Zl/sRyZ8ptWxV3H3ZaV3hsw2LUgKC6kvRh7isT2PfTWggFOmtmJPUFQz8bgHtl26Cs0dTUWJ/2QXqjO3Nm00j0XOlwWHOtzFfuWOxmuanAljHpmzEaFXzelbcwzN4GAQ+bD1pONTgwbJt6pemY67kbjPJVa/kbao7mIRR1ZzMZ0yyyZPKNXqYUrgDzh8PZJFpvlQFtw3tYDeCh6LasquYuTC/q+x1ANSnUrRHH3EatO5bGtW4aapL6NAC/1XoecKhy+f51J9HdZZPW+DH9hPCdFn+3CL04teCHuFR93FvVl1Sw1oPQ7d5bA2P+qwpWWjWUzIX0khRi9s3TlqD12e9GAiQfq1iLYJePb8mM9z63W/iMR2L+FOssiflWQ4TgajWbCTtCY47RtHh4tayA=
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh
script:
- "./_build.sh"
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  _deploy.sh
