language: r
cache:
  packages: true
  directories:
  - "$TRAVIS_BUILD_DIR/_bookdown_files"
sudo: false
env:
  global:
  - secure: "Ab9n99HpOrhuyV8bhHIFVLD783XaYTAoORY0DbYQpPszGTxtp0d7E47ylW7na2XBeQVCMPGXLUxoU6e+0tNruED/meNrXTcp4MBofV4M+FNYzMtVs49MFfQZ+rKzsWhmkApTapylkNHdq/e8Mi3xG1RyBAcWHLgNc8VJ7U/eUC7JAaU9UQg4QVcOh3Z78bRSj4/6HjNBlLVwPDtD2hAaHdKa8dilcon7LwC2YuvcfQsb3ZVnBg67g62pxI4OxZ/9ZZiPMUZnhLpYcb1jcliTVuVzIjFldZQQUSQQRzbaE1tZarny6H7530zMhKxxma/x8tKMGJC/txve3F8DRPgLli7ZDWcvzpk4bvBSvygsqjOboyTou69ZbEQa2O4h6/hztgipCdoGka/YFFxBAZtouwnKAogad4qobt2sKPYTk0meQyLwAtCOX7wFUnTuUCR/aIeR1VL8IiWx1w/sYXW4TOC9hyDn7LnmuxoyB7MEEY24XSNdsgTe5yMw5b3v6XUA5/PaZ0oeq7u8YaJLiFZveKX5Jzjv3iGmH8iCSJSudalpmTLW0OVJPWluiq2tOC94Ijo1DlSD6jxcfF8bC3zRCdbPKcRa9363Xmh/ql9pBEUz7176p9CBWk0JZZCN7tSLA3N/zORVZSmdHSY/5s4u1jK+JxZ37TpwDym8RBPMDJs="
before_script:
- chmod +x ./deployment/_build.sh
- chmod +x ./deployment/_deploy.sh
script:
- travis_wait 45 "./deployment/_build.sh"
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash ./deployment/_deploy.sh 
